# Generated by Django 5.1.6 on 2025-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='root_folder_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
