# Generated by Django 5.1.6 on 2025-03-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_root_folder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='root_folder_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='root_folder_uuid'),
        ),
    ]
